export const EXAMPLE = "EXAMPLE"
export const REGISTER_GRAPHIC_DESIGN_USER = "REGISTER_GRAPHIC_DESIGN_USER"
export const REGISTER_UIUX_DESIGN_USER = "REGISTER_UIUX_DESIGN_USER"
export const REGISTER_SEO_DESIGN_USER = "REGISTER_SEO_DESIGN_USER"
export const REGISTER_WEB_DESIGN_USER = "REGISTER_WEB_DESIGN_USER"
export const REGISTER_APP_DESIGN_USER = "REGISTER_APP_DESIGN_USER"
export const CONTACT_US_REGISTER_USER = "CONTACT_US_REGISTER_USER"
export const SUBSCRIBE_NEWSLETTER = "SUBSCRIBE_NEWSLETTER"
export const  GET_ALL_SUBSCRIBERS="GET_ALL_SUBSCRIBERS"
export const RESUME_CREATE="RESUME_CREATE"


export const MSQL_API_URL = "https://localhost:44375/"